//https://github."},com/gleeny/nevrevr/tree/master/collection/en

export default data = [
    {"phrase": "Je ne me suis jamais touché dans des toilettes publiques."},
    {"phrase": "Je n'ai jamais marché pieds nus dans la merde de chien."},
    {"phrase": "Je n'ai jamais goûté à la nourriture pour chiens ou chats."},
    {"phrase": "Je ne me suis jamais fait vomir dessus."},
    {"phrase": "Je n'ai jamais vomis sur quelqu'un."},
    {"phrase": "J'ai déjà mangé des insectes."},
    {"phrase": "Je n'ai jamais déjà utilisé mon téléphone aux toilettes."},
    {"phrase": "Je n'ai jamais porté les sous-vêtements de l'autre sexe."},
    {"phrase": "Je n'ai jamais utilisé mes mains comme un mouchoir en papier (par nécessité)."},
    {"phrase": "Je n'ai jamais fait pipi sur quelqu'un d'autre."},
    {"phrase": "Je n'ai jamais pratiquer le coït dans des toilettes."},
    {"phrase": "Je n'ai jamais essayé les drogues fortes."},
    {"phrase": "Je n'ai jamais essuyé mes aisselles avec une serviette au lieu de prendre une douche."},
    {"phrase": "Je n'ai jamais porté la même paire de sous-vêtements plus de 3 jours."},
    {"phrase": "Je n'ai jamais utilisé fait l'amour dans une salle de bain publique."},
    {"phrase": "Je n'ai jamais ravalé mon vomi."},
    {"phrase": "Je n'ai jamais utilisé des toilettes publiques sans papier toilette."},
    {"phrase": "Je n'ai jamais fait de tatouages."},
    {"phrase": "Je n'ai jamais fait de sauts en parachute."},
    {"phrase": "Je n'ai jamais dormi dans la rue complètement déchiré."},
    {"phrase": "Je n'ai jamais été aux états unis."},
    {"phrase": "Je n'ai jamais été bourré€ plus de 24h."},
    {"phrase": "Je n'ai jamais utilisé levier pour faire pipi."},
    {"phrase": "Je n'ai jamais rencontré de fétichiste des pieds."},
    {"phrase": "Je n'ai jamais ronger mes ongles de pieds."},
    {"phrase": "Je n'ai jamais retourné les sous-vêtements pour mieux les utiliser."},
    {"phrase": "Je n'ai jamais fait fumer mes poils pubiens à un(e) pote."},
    {"phrase": "Je n'ai jamais conduit bourré."},
    {"phrase": "Je n'ai jamais fait de bad trip."},
    {"phrase": "Je n'ai jamais utilisé de preservatif fluorescent."},
    {"phrase": "Je n'ai jamais fait l'amour dans un lieu public."},
    {"phrase": "Je n'ai jamais utilisé un briquet juste pour pécho en soirée."},
    {"phrase": "Je n'ai jamais fait la danse du limousin."},
    {"phrase": "Je n'ai jamais porté des souvetements du sexe opposé."},
    {"phrase": "Je n'ai jamais uriné dans la rue."},
    {"phrase": "Je n'ai jamais vomis dans la rue."},
    {"phrase": "Je n'ai jamais fait semblant qu'une pote était en galere pour esquiver un date."},
    {"phrase": "Je n'ai jamais fait une balade sue le dos d'un éléphant."},
    {"phrase": "Je n'ai jamais pisser sur un comissariat."},
    {"phrase": "Je n'ai jamais finis en cellule de dégrisement."},
    {"phrase": "Je n'ai jamais été bloquée dans un ascenseur."},
    {"phrase": "Je n'ai jamais nagé avec des dauphins/tortues."},
    {"phrase": "Je n'ai jamais utilisé la même capote plusieurs fois."},
    {"phrase": "Je n'ai jamais vu ou eu le freint pété."},
    {"phrase": "Je n'ai jamais fait de cuni."},
    {"phrase": "Je n'ai jamais volé ou changé de place des panneaux de signalisation."},
    {"phrase": "Je n'ai jamais mangé de space cake."},
    {"phrase": "Je n'ai jamais fait de pool party."},
    {"phrase": "Je n'ai jamais dormi chez un ou des inconnus rencontrés en soirée."},
    {"phrase": "Je n'ai jamais était à un concert d'un bots band."},
    {"phrase": "Je n'ai jamais eu de poster des one, de tokyo hotel ou de justin dans ma chambre."},
    {"phrase": "Je n'ai jamais rasé ou épilé mon copain ou ma copine."},
    {"phrase": "Je n'ai jamais maquillé mon copain ou ma copine."},
    {"phrase": "Je n'ai jamais fait de surf."},
    {"phrase": "Je n'ai jamais été en spring break."},
    {"phrase": "Je n'ai jamais pris de la drogue en boite."},
    {"phrase": "Je n'ai jamais dansé dans la rue, bourré en rentrant de soirée."},
    {"phrase": "Je n'ai jamais volé un cadie et fini dedans."},
    {"phrase": "Je n'ai jamais dormi pendant l'acte."},
    {"phrase": "Je n'ai jamais été en Amérique Latine."},
    {"phrase": "Je n'ai jamais été arrêtées par les flics."},
    {"phrase": "Je n'ai jamais été recallé à l'entrée d'une boite."},
    {"phrase": "Je n'ai jamais été viré d'une boite."},
    {"phrase": "Je n'ai jamais envoyé un sms ou snap aux toilettes."},
    {"phrase": "Je n'ai jamais envoyé de nude."},
    {"phrase": "Je n'ai jamais fait accidentellement caca dans mon pantalon."},
    {"phrase": "Je n'ai jamais envoyé un nude à la mauvaise personne."},
    {"phrase": "Je n'ai jamais envoyé un message à la mauvaise personne."},
    {"phrase": "Je n'ai jamais fait l'amour à l'arrière d'une voiture."},
    {"phrase": "Je n'ai jamais fait l'amour dans un lieu public."},
    {"phrase": "Je n'ai jamais fait l'amour dans des toilettes."},
    {"phrase": "Je n'ai jamais été surpris par mes parents en train de me masturber."},
    {"phrase": "Je n'ai jamais été surpris par mes parents, avec mon copain/copine en plein acte."},
    {"phrase": "Je n'ai jamais après une soirée bien arrosée, été complètement parano en rentrant chez moi."},
    {"phrase": "Je n'ai jamais vu de porno."},
    {"phrase": "Je n'ai jamais enregistré des vidéos de moi-même en train de chanter ou de danser."},
    {"phrase": "Je n'ai jamais eu le nez cassé."},
    {"phrase": "Je n'ai jamais été recousu."},
    {"phrase": "Je n'ai jamais pété le nez de quelqu'un d'autre."},
    {"phrase": "Je n'ai jamais ouvert la bouteille de bière avec les dents."},
    {"phrase": "Je n'ai jamais eu de coupe de cheveux originale/douteuse/dont j'ai honte."},
    {"phrase": "Je n'ai jamais été obsédé par les One Direction ou Justin Bieber."},
    {"phrase": "Je n'ai jamais joué à Minecraft/Fortnite."},
    {"phrase": "Je n'ai jamais passé la nuit à jouer aux jeux vidéo."},
    {"phrase": "Je n'ai jamais passé 48h ou plus à jouer aux jeux vidéo."},
    {"phrase": "Je n'ai jamais espionné quelqu'un sur fb."},
    {"phrase": "Je n'ai jamais trompé ma femme dans sims."},
    {"phrase": "Je n'ai jamais eu de rdv Tinder."},
    {"phrase": "Je ne suis jamais sorti avec un étranger."},
    {"phrase": "Je n'ai jamais pris une ligne ou un shot sur quelqu'un."},
    {"phrase": "Je n'ai jamais eu un coup d'une nuit."},
    {"phrase": "Je n'ai jamais sucer un garçon ou une fille."},
    {"phrase": "Je n'ai jamais eu d'expérience homosexuelle."},
    {"phrase": "Je n'ai jamais eu le coup de foudre pour quelqu'un de 10 ans de plus que moi."},
    {"phrase": "Je n'ai jamais eu de relation avec quelqu'un de plus 10 ans de plus que moi."},
    {"phrase": "Je n'ai jamais sifflé un mec."},
    {"phrase": "Je n'ai jamais raté mon arrêt parce que je dormais."},
    {"phrase": "Je n'ai jamais fréquenté plus d'une personne à la fois."},
    {"phrase": "Je n'ai jamais porté le même jean pendant un semaine."},
    {"phrase": "Je n'ai jamais acheté de lingerie pour le sexe opposé."},
    {"phrase": "Je n'ai jamais été dans un sex shop."},
    {"phrase": "Je n'ai jamais acheté quelque chose dans un sex shop."},
    {"phrase": "Je n'ai jamais fait de prélis au ciné."},
    {"phrase": "Je n'ai jamais joué au strip poker."},
    {"phrase": "Je ne me suis jamais retrouvé nu au strip poker."},
    {"phrase": "Je n'ai jamais flashé sur un de mes enseignant/e."},
    {"phrase": "Je n'ai jamais eu de relation avec un/e enseignant/e."},
    {"phrase": "Je n'ai jamais simulé."},
    {"phrase": "Je ne l'ai jamais fait dehors."},
    {"phrase": "Je n'ai jamais fait de vidéos coquines."}
];